# -*- coding: utf-8 -*-
"""Assignment8

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HM8m3QL2uF_xl0_gwrDDenEJWs4dOFCK
"""

# -*- coding: utf-8 -*-
"""Assignment-9.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1MzVYYLJBg4EagDwG1793x0kYmiBAR6w9
"""

import numpy as np
A = ([[0,1,2],[1,2,3],[3,1,1]])
print("Original matrix:")
print(A)
result =  np.linalg.inv(A)
print("inverse of the said matrix:")
print(result)

# Decomposition of the said matrix
q, r = np.linalg.qr(A)
print('\nQ:\n', q)
print('\nR:\n', r)